services:
- type: web
  name: sample-node-react
  env: docker
  dockerfilePath: ./Dockerfile.prod # optional
  dockerContext: .
  repo: https://github.com/ardydedase/node-react-ssr.git
  plan: starter
  branch: master
  healthCheckPath: /healthcheck
  