declare module "handlebars";
declare module "react-bootstrap/Card";
declare module "react-bootstrap/Button";
declare module "react-bootstrap/Navbar";
declare module "react-bootstrap/Nav";
declare module "react-bootstrap/NavDropdown";
declare module "react-bootstrap/Container";
declare module "react-bootstrap/Row";
declare module "react-bootstrap/Col";
declare module "react-bootstrap/Alert";
declare module "react-bootstrap/Spinner";
declare module "react-bootstrap/Form";
declare module "react-bootstrap/InputGroup";
declare module "react-bootstrap/FormControl";
declare module "react-bootstrap/Card";
declare module "react-bootstrap/ButtonToolbar";
declare module "react-bootstrap/ButtonGroup";
declare module "react-icons/ai"
declare module "react-icons/fa"