# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  reference-app-directory: ./express-react-ssr-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1.2.0

      - name: Install cookiecutter
        run: pip install cookiecutter

      - name: Cookiecut the template
        run: cookiecutter $GITHUB_WORKSPACE --no-input

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install npm packages
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm install

      - name: Format and lint
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm run lint

      - name: Run tests
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm test

      - name: Run build
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm run build

      - name: Checkout reference app
        uses: actions/checkout@v2
        with:
          repository: ardydedase/express-react-ssr-reference
          ref: main
          path: express-react-ssr-reference

      - name: Sync repos
        run: |
          rsync -a --delete ${{env.reference-app-directory}} ./express-react-ssr-reference

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        working-directory: ./express-react-ssr-reference
        run: |
          ls -al
          git add .
          git commit -m "Changes from PR #${PR}"
          git push origin main
