# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  reference-app-directory: ./express-react-ssr-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git
        uses: srt32/git-actions@v0.0.3

      - name: Git status
        run: git clone git@github.com:ardydedase/express-react-ssr-reference.git

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1.2.0

      - name: Install cookiecutter
        run: pip install cookiecutter

      - name: Cookiecut the template
        run: cookiecutter $GITHUB_WORKSPACE --no-input

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install npm packages
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm install

      - name: Format and lint
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm run lint

      - name: Run tests
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm test

      - name: Run build
        working-directory: ${{env.reference-app-directory}}
        run: |
          npm run build
